function graficos = dibujar_entorno( ...
    graficos, escenario, obstaculosDinamicos)
%DIBUJAR_ENTORNO Dibuja el mapa y los obstaculos de la simulacion.
%
%   graficos = DIBUJAR_ENTORNO(graficos,escenario)
%
%   graficos = DIBUJAR_ENTORNO( ...
%       graficos,escenario,obstaculosDinamicos)
%
%   Completa la figura creada por inicializar_figura.m mediante objetos
%   graficos persistentes para:
%
%       - el contorno rectangular del mapa;
%       - los obstaculos estaticos rectangulares;
%       - las etiquetas S1, S2, ...;
%       - los obstaculos dinamicos circulares;
%       - las flechas de velocidad;
%       - las etiquetas D1, D2, ...;
%       - la posicion inicial START;
%       - la meta GOAL.
%
%   La apariencia conserva el formato general de los codigos funcionales
%   de referencia:
%
%       obstaculos estaticos    gris oscuro con texto blanco;
%       obstaculos dinamicos    rojo con transparencia;
%       flechas dinamicas       rojas;
%       inicio                  circulo verde;
%       meta                    pentagrama rojo;
%       borde del mapa          negro.
%
%   Los objetos se crean una unica vez. actualizar_graficos.m modificara
%   posteriormente las posiciones de los obstaculos dinamicos mediante
%   XData, YData, UData y VData, sin utilizar clf.
%
%   Entradas:
%       graficos
%           Estructura obtenida mediante inicializar_figura.m.
%
%       escenario
%           Estructura obtenida mediante escenarios.m. Debe contener:
%
%               escenario.limites
%               escenario.inicio
%               escenario.meta
%               escenario.obstaculosEstaticos
%               escenario.obstaculosDinamicos
%
%       obstaculosDinamicos
%           Vector opcional de estructuras con los campos:
%
%               id
%               pos
%               vel
%               radio
%
%           Si se omite, se utilizan los obstaculos iniciales incluidos
%           en escenario.obstaculosDinamicos.
%
%   Salida:
%       graficos
%           Misma estructura de entrada, ampliada con los manejadores:
%
%               graficos.objetos.bordeMapa
%               graficos.objetos.obstaculosEstaticos
%               graficos.objetos.etiquetasEstaticos
%               graficos.objetos.obstaculosDinamicos
%               graficos.objetos.flechasDinamicos
%               graficos.objetos.etiquetasDinamicos
%               graficos.objetos.inicio
%               graficos.objetos.meta
%               graficos.objetos.etiquetaInicio
%               graficos.objetos.etiquetaMeta
%
%   Modo batch:
%       Si graficos.activa es false, no se crea ningun objeto grafico y la
%       funcion devuelve inmediatamente la estructura recibida.
%
%   Ejemplo:
%
%       cfg = parametros_generales("visual");
%       escenario = escenarios("media");
%
%       graficos = inicializar_figura( ...
%           escenario,cfg,"RRT* + MPC");
%
%       graficos = dibujar_entorno( ...
%           graficos,escenario);
%
%   Esta funcion no dibuja el robot, el camino global, el arbol o roadmap
%   ni la trayectoria ejecutada.

if nargin < 3 || isempty(obstaculosDinamicos)
    if isstruct(escenario) && ...
            isfield(escenario,'obstaculosDinamicos')
        obstaculosDinamicos = ...
            escenario.obstaculosDinamicos;
    else
        obstaculosDinamicos = ...
            struct('id',{},'pos',{},'vel',{},'radio',{});
    end
end

%% Validacion y normalizacion
[graficos, escenario, obstaculosDinamicos] = ...
    validar_entradas( ...
        graficos,escenario,obstaculosDinamicos);

if ~graficos.activa
    return;
end

ejes = graficos.ejes;
capas = graficos.capas;
estilo = graficos.estilo;
objetos = graficos.objetos;

%% Eliminacion segura de una representacion anterior
% Permite volver a llamar a la funcion, por ejemplo al cambiar de escenario,
% sin duplicar objetos en la figura.
camposEntorno = { ...
    'bordeMapa', ...
    'obstaculosEstaticos', ...
    'etiquetasEstaticos', ...
    'obstaculosDinamicos', ...
    'flechasDinamicos', ...
    'etiquetasDinamicos', ...
    'inicio', ...
    'meta', ...
    'etiquetaInicio', ...
    'etiquetaMeta'};

for i = 1:numel(camposEntorno)
    campo = camposEntorno{i};

    if isfield(objetos,campo)
        eliminar_manejadores(objetos.(campo));
    end
end

%% ========================================================================
% CONTORNO DEL MAPA
% ========================================================================

limites = escenario.limites;

posicionMapa = [ ...
    limites(1), ...
    limites(3), ...
    limites(2)-limites(1), ...
    limites(4)-limites(3)];

objetos.bordeMapa = rectangle( ...
    'Parent',capas.entorno, ...
    'Position',posicionMapa, ...
    'FaceColor','none', ...
    'EdgeColor',estilo.colorBordeMapa, ...
    'LineWidth',estilo.anchoBordeMapa, ...
    'Tag','borde_mapa');

%% ========================================================================
% OBSTACULOS ESTATICOS
% ========================================================================

estaticos = escenario.obstaculosEstaticos;
numeroEstaticos = size(estaticos,1);

objetos.obstaculosEstaticos = ...
    gobjects(numeroEstaticos,1);

objetos.etiquetasEstaticos = ...
    gobjects(numeroEstaticos,1);

for i = 1:numeroEstaticos
    rectangulo = estaticos(i,:);

    objetos.obstaculosEstaticos(i) = rectangle( ...
        'Parent',capas.entorno, ...
        'Position',rectangulo, ...
        'FaceColor',estilo.colorObstaculoEstatico, ...
        'EdgeColor','k', ...
        'LineWidth',1.0, ...
        'Tag',sprintf('obstaculo_estatico_%d',i));

    centroX = rectangulo(1)+rectangulo(3)/2;
    centroY = rectangulo(2)+rectangulo(4)/2;

    objetos.etiquetasEstaticos(i) = text( ...
        'Parent',capas.entorno, ...
        'Position',[centroX centroY 0], ...
        'String',sprintf('S%d',i), ...
        'Color',estilo.colorTextoEstatico, ...
        'FontWeight','bold', ...
        'FontSize',estilo.tamanoFuenteObjetos, ...
        'Interpreter','none', ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'Clipping','on', ...
        'Tag',sprintf('etiqueta_estatico_%d',i));
end

%% ========================================================================
% OBSTACULOS DINAMICOS
% ========================================================================

numeroDinamicos = numel(obstaculosDinamicos);

objetos.obstaculosDinamicos = ...
    gobjects(numeroDinamicos,1);

objetos.flechasDinamicos = ...
    gobjects(numeroDinamicos,1);

objetos.etiquetasDinamicos = ...
    gobjects(numeroDinamicos,1);

angulosCirculo = estilo.anguloCirculo;
escalaFlecha = obtener_escala_flecha(estilo);

for i = 1:numeroDinamicos
    dinamico = obstaculosDinamicos(i);

    [xCirculo,yCirculo] = coordenadas_circulo( ...
        dinamico.pos,dinamico.radio,angulosCirculo);

    objetos.obstaculosDinamicos(i) = patch( ...
        'Parent',capas.obstaculosDinamicos, ...
        'XData',xCirculo, ...
        'YData',yCirculo, ...
        'FaceColor',estilo.colorObstaculoDinamico, ...
        'FaceAlpha',estilo.alphaObstaculoDinamico, ...
        'EdgeColor','k', ...
        'LineWidth',1.0, ...
        'Tag',sprintf('obstaculo_dinamico_%d',i));

    componenteX = escalaFlecha*dinamico.vel(1);
    componenteY = escalaFlecha*dinamico.vel(2);

    % quiver se crea inicialmente en los ejes y despues se incorpora a la
    % capa de obstaculos dinamicos para conservar el orden visual.
    flecha = quiver( ...
        ejes, ...
        dinamico.pos(1), ...
        dinamico.pos(2), ...
        componenteX, ...
        componenteY, ...
        0, ...
        'Color',estilo.colorFlechaDinamica, ...
        'LineWidth',estilo.anchoFlecha, ...
        'MaxHeadSize',0.8);

    flecha.Parent = capas.obstaculosDinamicos;
    flecha.Tag = sprintf('flecha_dinamico_%d',i);

    objetos.flechasDinamicos(i) = flecha;

    identificador = obtener_id_dinamico( ...
        dinamico,i);

    objetos.etiquetasDinamicos(i) = text( ...
        'Parent',capas.obstaculosDinamicos, ...
        'Position',[dinamico.pos 0], ...
        'String',char(identificador), ...
        'Color',estilo.colorTextoDinamico, ...
        'FontWeight','bold', ...
        'FontSize',estilo.tamanoFuenteObjetos, ...
        'Interpreter','none', ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'Clipping','on', ...
        'Tag',sprintf('etiqueta_dinamico_%d',i));
end

%% ========================================================================
% POSICION INICIAL Y META
% ========================================================================

inicio = escenario.inicio(1:2);
meta = escenario.meta;

objetos.inicio = line( ...
    'Parent',capas.entorno, ...
    'XData',inicio(1), ...
    'YData',inicio(2), ...
    'LineStyle','none', ...
    'Marker','o', ...
    'MarkerSize',estilo.tamanoInicio, ...
    'MarkerEdgeColor',estilo.colorInicio, ...
    'MarkerFaceColor',estilo.colorInicio, ...
    'Tag','inicio');

objetos.meta = line( ...
    'Parent',capas.entorno, ...
    'XData',meta(1), ...
    'YData',meta(2), ...
    'LineStyle','none', ...
    'Marker','p', ...
    'MarkerSize',estilo.tamanoMeta, ...
    'MarkerEdgeColor',estilo.colorMeta, ...
    'MarkerFaceColor',estilo.colorMeta, ...
    'Tag','meta');

desplazamientoEtiqueta = 0.015*min( ...
    limites(2)-limites(1), ...
    limites(4)-limites(3));

objetos.etiquetaInicio = text( ...
    'Parent',capas.entorno, ...
    'Position',[ ...
        inicio(1)+desplazamientoEtiqueta, ...
        inicio(2)+desplazamientoEtiqueta, ...
        0], ...
    'String','START', ...
    'Color','k', ...
    'FontWeight','bold', ...
    'FontSize',estilo.tamanoFuenteObjetos, ...
    'Interpreter','none', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom', ...
    'Clipping','on', ...
    'Tag','etiqueta_inicio');

objetos.etiquetaMeta = text( ...
    'Parent',capas.entorno, ...
    'Position',[ ...
        meta(1)+desplazamientoEtiqueta, ...
        meta(2)+desplazamientoEtiqueta, ...
        0], ...
    'String','GOAL', ...
    'Color','k', ...
    'FontWeight','bold', ...
    'FontSize',estilo.tamanoFuenteObjetos, ...
    'Interpreter','none', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom', ...
    'Clipping','on', ...
    'Tag','etiqueta_meta');

%% Incorporacion de los objetos a la salida
graficos.objetos = objetos;

graficos.entornoDibujado = true;
graficos.numeroObstaculosEstaticos = numeroEstaticos;
graficos.numeroObstaculosDinamicos = numeroDinamicos;
graficos.escalaFlechaVelocidad = escalaFlecha;

% El renderizado se difiere hasta el drawnow del bucle principal.
end

%% ========================================================================
% UTILIDADES GRAFICAS
% ========================================================================

function [x,y] = coordenadas_circulo(centro,radio,angulos)
%COORDENADAS_CIRCULO Calcula el contorno de un circulo.

x = centro(1)+radio*cos(angulos);
y = centro(2)+radio*sin(angulos);
end

function identificador = obtener_id_dinamico(dinamico,indice)
%OBTENER_ID_DINAMICO Recupera el id almacenado o genera D1, D2, ...

if isfield(dinamico,'id') && ...
        strlength(strtrim(string(dinamico.id))) > 0
    identificador = string(dinamico.id);
else
    identificador = "D"+indice;
end
end

function escala = obtener_escala_flecha(estilo)
%OBTENER_ESCALA_FLECHA Define la longitud visual de la velocidad.
%
% La implementacion funcional original multiplicaba la velocidad por 10
% porque sus valores representaban desplazamiento por iteracion. En el
% proyecto modular las velocidades se expresan en m/s. Por ello se usa el
% horizonte temporal definido por inicializar_figura.m.

if isfield(estilo,'horizonteFlechaVelocidad') && ...
        isnumeric(estilo.horizonteFlechaVelocidad) && ...
        isscalar(estilo.horizonteFlechaVelocidad) && ...
        isfinite(estilo.horizonteFlechaVelocidad) && ...
        estilo.horizonteFlechaVelocidad > 0
    escala = double(estilo.horizonteFlechaVelocidad);
else
    escala = 1.0;
end
end

function eliminar_manejadores(manejadores)
%ELIMINAR_MANEJADORES Borra un conjunto de objetos si siguen siendo validos.

if isempty(manejadores)
    return;
end

validos = isgraphics(manejadores);

if any(validos(:))
    delete(manejadores(validos));
end
end

%% ========================================================================
% VALIDACION
% ========================================================================

function [graficos,escenario,dinamicos] = validar_entradas( ...
    graficos,escenario,dinamicos)
%VALIDAR_ENTRADAS Comprueba la coherencia del modulo.

%% Estructura grafica
if ~isstruct(graficos) || ~isscalar(graficos) || ...
        ~isfield(graficos,'activa')
    error('dibujar_entorno:GraficosNoValidos', ...
        ['graficos debe ser la estructura obtenida mediante ' ...
         'inicializar_figura.m.']);
end

graficos.activa = validar_logico( ...
    graficos.activa,'graficos.activa');

if ~graficos.activa
    return;
end

camposGraficos = { ...
    'inicializada', ...
    'figura', ...
    'ejes', ...
    'capas', ...
    'objetos', ...
    'estilo'};

for i = 1:numel(camposGraficos)
    if ~isfield(graficos,camposGraficos{i})
        error('dibujar_entorno:GraficosIncompletos', ...
            'Falta graficos.%s.',camposGraficos{i});
    end
end

if ~graficos.inicializada || ...
        ~isgraphics(graficos.figura,'figure') || ...
        ~isgraphics(graficos.ejes,'axes')
    error('dibujar_entorno:FiguraNoInicializada', ...
        ['La figura no esta inicializada o ha sido cerrada. ' ...
         'Ejecute de nuevo inicializar_figura.m.']);
end

if ~isstruct(graficos.capas) || ...
        ~isfield(graficos.capas,'entorno') || ...
        ~isfield(graficos.capas,'obstaculosDinamicos') || ...
        ~isgraphics(graficos.capas.entorno) || ...
        ~isgraphics(graficos.capas.obstaculosDinamicos)
    error('dibujar_entorno:CapasNoValidas', ...
        'Las capas graficas del entorno no son validas.');
end

if ~isstruct(graficos.objetos) || ...
        ~isstruct(graficos.estilo)
    error('dibujar_entorno:EstructuraInternaNoValida', ...
        'graficos.objetos y graficos.estilo deben ser estructuras.');
end

camposEstilo = { ...
    'colorBordeMapa', ...
    'colorObstaculoEstatico', ...
    'colorTextoEstatico', ...
    'colorObstaculoDinamico', ...
    'colorFlechaDinamica', ...
    'colorTextoDinamico', ...
    'colorInicio', ...
    'colorMeta', ...
    'anchoBordeMapa', ...
    'anchoFlecha', ...
    'alphaObstaculoDinamico', ...
    'tamanoInicio', ...
    'tamanoMeta', ...
    'tamanoFuenteObjetos', ...
    'anguloCirculo'};

for i = 1:numel(camposEstilo)
    if ~isfield(graficos.estilo,camposEstilo{i})
        error('dibujar_entorno:EstiloIncompleto', ...
            'Falta graficos.estilo.%s.',camposEstilo{i});
    end
end

%% Escenario
if ~isstruct(escenario) || ~isscalar(escenario)
    error('dibujar_entorno:EscenarioNoValido', ...
        'escenario debe proceder de escenarios.m.');
end

camposEscenario = { ...
    'limites', ...
    'inicio', ...
    'meta', ...
    'obstaculosEstaticos'};

for i = 1:numel(camposEscenario)
    if ~isfield(escenario,camposEscenario{i})
        error('dibujar_entorno:EscenarioIncompleto', ...
            'Falta escenario.%s.',camposEscenario{i});
    end
end

if ~isnumeric(escenario.limites) || ...
        ~isreal(escenario.limites) || ...
        numel(escenario.limites) ~= 4 || ...
        any(~isfinite(escenario.limites(:)))
    error('dibujar_entorno:LimitesNoValidos', ...
        'escenario.limites debe ser [xmin xmax ymin ymax].');
end

escenario.limites = reshape( ...
    double(escenario.limites),1,4);

if escenario.limites(1) >= escenario.limites(2) || ...
        escenario.limites(3) >= escenario.limites(4)
    error('dibujar_entorno:OrdenLimitesNoValido', ...
        'Debe cumplirse xmin < xmax e ymin < ymax.');
end

if ~isnumeric(escenario.inicio) || ...
        ~isreal(escenario.inicio) || ...
        numel(escenario.inicio) < 2 || ...
        any(~isfinite(escenario.inicio(:)))
    error('dibujar_entorno:InicioNoValido', ...
        'escenario.inicio debe contener al menos [x y].');
end

escenario.inicio = ...
    reshape(double(escenario.inicio),1,[]);

if ~isnumeric(escenario.meta) || ...
        ~isreal(escenario.meta) || ...
        numel(escenario.meta) ~= 2 || ...
        any(~isfinite(escenario.meta(:)))
    error('dibujar_entorno:MetaNoValida', ...
        'escenario.meta debe tener formato [x y].');
end

escenario.meta = reshape( ...
    double(escenario.meta),1,2);

estaticos = escenario.obstaculosEstaticos;

if isempty(estaticos)
    escenario.obstaculosEstaticos = zeros(0,4);
elseif ~isnumeric(estaticos) || ...
        ~isreal(estaticos) || ...
        size(estaticos,2) ~= 4 || ...
        any(~isfinite(estaticos(:))) || ...
        any(estaticos(:,3:4) <= 0,'all')
    error('dibujar_entorno:EstaticosNoValidos', ...
        ['escenario.obstaculosEstaticos debe ser una matriz N x 4 ' ...
         'con formato [x y ancho alto].']);
else
    escenario.obstaculosEstaticos = double(estaticos);
end

%% Obstaculos dinamicos
if isempty(dinamicos)
    dinamicos = struct( ...
        'id',{},'pos',{},'vel',{},'radio',{});
elseif ~isstruct(dinamicos)
    error('dibujar_entorno:DinamicosNoValidos', ...
        'obstaculosDinamicos debe ser un vector de estructuras.');
else
    for i = 1:numel(dinamicos)
        camposDinamico = {'pos','vel','radio'};

        for j = 1:numel(camposDinamico)
            if ~isfield(dinamicos(i),camposDinamico{j})
                error('dibujar_entorno:CampoDinamicoAusente', ...
                    ['Falta el campo "%s" en el obstaculo ' ...
                     'dinamico %d.'],camposDinamico{j},i);
            end
        end

        if ~isnumeric(dinamicos(i).pos) || ...
                ~isreal(dinamicos(i).pos) || ...
                numel(dinamicos(i).pos) ~= 2 || ...
                any(~isfinite(dinamicos(i).pos(:)))
            error('dibujar_entorno:PosicionDinamicaNoValida', ...
                'La posicion de D%d debe tener formato [x y].',i);
        end

        if ~isnumeric(dinamicos(i).vel) || ...
                ~isreal(dinamicos(i).vel) || ...
                numel(dinamicos(i).vel) ~= 2 || ...
                any(~isfinite(dinamicos(i).vel(:)))
            error('dibujar_entorno:VelocidadDinamicaNoValida', ...
                'La velocidad de D%d debe tener formato [vx vy].',i);
        end

        if ~isnumeric(dinamicos(i).radio) || ...
                ~isscalar(dinamicos(i).radio) || ...
                ~isreal(dinamicos(i).radio) || ...
                ~isfinite(dinamicos(i).radio) || ...
                dinamicos(i).radio <= 0
            error('dibujar_entorno:RadioDinamicoNoValido', ...
                'El radio de D%d debe ser positivo.',i);
        end

        dinamicos(i).pos = reshape( ...
            double(dinamicos(i).pos),1,2);

        dinamicos(i).vel = reshape( ...
            double(dinamicos(i).vel),1,2);

        dinamicos(i).radio = ...
            double(dinamicos(i).radio);
    end
end
end

function valor = validar_logico(valor,nombre)
%VALIDAR_LOGICO Convierte un escalar logico o binario.

if islogical(valor) && isscalar(valor)
    return;
end

if isnumeric(valor) && isscalar(valor) && ...
        isreal(valor) && isfinite(valor) && ...
        (valor == 0 || valor == 1)
    valor = logical(valor);
    return;
end

error('dibujar_entorno:IndicadorNoValido', ...
    '%s debe ser un escalar logico o binario.',nombre);
end
